src/components/quiz-review/question-review/question-review.tsx
added 'why' to open question review
=> fix(FEV-1208): WHY (explanation) is not displayed on the player

src/components/timeline/timeline-marker.tsx, src/ivq.tsx, src/types/quizTypesUI.ts
according to W3 documentation - Screen readers ignores Presentational children (https://www.w3.org/TR/wai-aria-1.1/#childrenArePresentational). To force Screen readers read ivq timeline-markers slider component receive new aria-valuetext value.
=> fix(FEV-1243): A11y - Timeline questions are not readable

src/components/ivq-bottom-bar/ivq-bottom-bar.tsx, src/components/quiz-question/quiz-question-wrapper.tsx, src/components/quiz-review/question-list-review/question-list-review.tsx, src/components/quiz-review/question-review/question-review.tsx, src/components/quiz-submit/quiz-submit.tsx, src/components/welcome-screen/welcome-screen.tsx
Safari has issue with focus on `<button>` elements, changed `<button>` to `<div>` + added a11y wrapper
=> fix(FEV-1247): Safari| Continue button is not accessible

src/components/ivq-overlay/ivq-overlay.scss
**the issue:**
on chrome browser, when ivq overlay is displayed, a scrollbar appears on the side.
**solution:**
add `overflow: hidden` to override core's css.
Solves [FEV-1607](https://kaltura.atlassian.net/browse/FEV-1607)
=> fix(FEV-1607): on chrome browser only, there is a scroll bar inside the quiz questions

package.json, src/components/quiz-question/multi-choice/multi-choice.tsx, src/components/quiz-question/true-false/true-false.tsx, yarn.lock
**the issue:**
when navigating using tab keyboard to an answer option, screen reader Jaws guides to use the arrow keys to navigate between the answers options.
**solution:**
- update common repo
- use up/down keyboard handlers for multiple choices questions
- use new left/right keyboard handlers for true/false questions
Solves [FEV-1603](https://kaltura.atlassian.net/browse/FEV-1603)
=> fix(FEV-1603): when navigating to an answer option, screen reader guides to use the arrow keys

translations/es.i18n.json
Added missing translation to some strings in Spanish 
Solves [SUP-37655](https://kaltura.atlassian.net/browse/SUP-37655)
[SUP-37655]: https://kaltura.atlassian.net/browse/SUP-37655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-37655): missing spanish translations for ivq (FEC-37655)

src/components/welcome-screen/welcome-screen.scss
issue:
on youtube video with quiz the welcome screen didnt display
solution:
add z-index for welcome screen and update z-index for play button so the welcome screen will be show on top on the video
=> fix(SUP-38205):Youtube IVQ missing welcome screen

src/components/ivq-overlay/ivq-overlay.scss, src/components/ivq-overlay/ivq-overlay.tsx
when injecting a Slate component, which is being injected inside OverlayPortal area, it is being overlayed with ivq overlay.
slate component should be on top of it. Hence, wrapping `IvqOverlay` component with `OverlayPortal` to place it inside the overlay portal area.
Part of [FEC-13313](https://kaltura.atlassian.net/browse/FEC-13313)
[FEC-13313]: https://kaltura.atlassian.net/browse/FEC-13313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FEC-13313): wrap IvqOverlay with OverlayPortal

cypress/e2e/env.ts, cypress/e2e/ivq-question-changed-event.cy.ts, cypress/e2e/ivq-review.cy.ts, cypress/e2e/ivq.cy.ts, package.json, src/components/ivq-popup/ivq-popup.tsx, src/components/ivq-popup/ivq-pupup.scss, src/components/quiz-submit/quiz-submit.scss, src/components/quiz-submit/quiz-submit.tsx, translations/en.i18n.json, yarn.lock
solves: https://kaltura.atlassian.net/browse/FEC-13595
solves: https://kaltura.atlassian.net/browse/FEC-13593
=> fix(FEC-13595): IVQ popup changes (FEC-13593)

src/data-sync-manager.ts
**the issue:**
When `PreventFwdSeek` set to `true`, "Quiz completed" toast is displayed although not all of the question were answered.
**solution:**
use new redux state isPreventSeek to enable seek control in ivq.
**dependent on PR:** https://github.com/kaltura/playkit-js-ui/pull/867
Solves [FEC-13781](https://kaltura.atlassian.net/browse/FEC-13781)
[FEC-13781]: https://kaltura.atlassian.net/browse/FEC-13781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FEC-13781): add validation to new isPreventSeek state

src/components/quiz-question/multi-choice/multi-choice.tsx, src/components/quiz-question/open-question/open-question.tsx, src/components/quiz-question/reflection-point/reflection-point.tsx, src/components/quiz-question/true-false/true-false.tsx, src/utils.ts
**the issue:**
adding a question that contains a link in the form of [link title|http://www.example.com/] to IVQ entry, doesn't render it as a link element <a>.
**solution:**
As in v2, added a util function that parses the questions and converts them to a link element if they correspond to the specific link syntax, supporting all 4 types of questions.
Solves [SUP-43316](https://kaltura.atlassian.net/browse/SUP-43316)
[SUP-43316]: https://kaltura.atlassian.net/browse/SUP-43316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-43316): support links in IVQ questions

src/components/welcome-screen/welcome-screen.tsx
pass new prop to `Overlay` component in `welcomeScreen` component - `dontCheckOverlayPortal`, which tells `Overlay` component to not check `overlayPortal` when removing `overlay-active` class, since it is being rendered outside of overlayPortal area.
**NOTE:** left a TODO note to check why the `Overlay` is not being rendered under `OverlayPortal`, as we usually do.
Resolves [FEC-14172](https://kaltura.atlassian.net/browse/FEC-14172)
related pr: https://github.com/kaltura/playkit-js-ui/pull/950
[FEC-14172]: https://kaltura.atlassian.net/browse/FEC-14172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FEC-141472): pass new prop to overlay

src/components/ivq-popup/ivq-popup.tsx
**Issue:**
Screen reader doesn't announce the popup alerts like "quiz completed/quiz submitted" and etc so screen reader users are not aware to this info.
**Fix:** 
Add role alert on the pop element so when it pops the screen reader will announce the content immediately.
Solves [ADA-1920](https://kaltura.atlassian.net/browse/ADA-1920)
[ADA-1920]: https://kaltura.atlassian.net/browse/ADA-1920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ADA-1920): University of California - Berkeley | Boundaries Quiz Completed & Submitted Dialogs are not exposed to Screen Reader Users

src/components/quiz-question/multi-choice/multi-choice.tsx, src/components/quiz-question/open-question/open-question.tsx, src/components/quiz-question/quiz-question-wrapper.tsx, src/components/quiz-question/reflection-point/reflection-point.tsx, src/components/quiz-question/true-false/true-false.tsx
Issue: 
When question overlay is opened, focus is not moved to first element in the overlay.
Root cause: 
tabindex=0 was removed from legend element since it's not an interactive element.
Fix:
Move the focus to first interactive element in the overlay instead of to legend element.
Solves [FEC-14262](https://kaltura.atlassian.net/browse/FEC-14262)
[FEC-14262]: https://kaltura.atlassian.net/browse/FEC-14262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FEC-14262): Player v7 | Quiz | Wrong first element focus on quiz questions overlay.

src/components/quiz-question/multi-choice/multi-choice.tsx
Change the aria-label of answer in multi choice to be the letter + answer content instead "Answer number x"
Solves [ADA-1990](https://kaltura.atlassian.net/browse/ADA-1990)
[ADA-1990]: https://kaltura.atlassian.net/browse/ADA-1990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ADA-1990): [IU] Redundant Screen Reader Announcement for Quiz Player Answer Options

src/data-sync-manager.ts, src/ivq.tsx, src/quiz-middleware.ts, translations/en.i18n.json
Issue:
When user tries to seek but prevent due to the quiz prevent seeking checkbox on KMS, he is unable to seek.
Fix:
Suppose to show an alert pop up with default message.
solved-[SUP-45709](https://kaltura.atlassian.net/browse/SUP-45709)
[SUP-45709]: https://kaltura.atlassian.net/browse/SUP-45709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-45709): IVQ Editor - No Seeking forward Alert for V7 player

src/components/ivq-bottom-bar/ivq-bottom-bar.tsx, src/components/quiz-question/quiz-question-wrapper.tsx, src/components/quiz-review/question-review/question-review.tsx, src/components/quiz-review/quiz-review.tsx, src/ivq.tsx, src/questions-visual-manager.tsx, translations/es.i18n.json
**Issue:**
The question appears a few seconds earlier than expected on the timeline.
Root Cause:
The issue stems from the player hover state not being updated. As a result:
The bottom bar doesn’t adjust its width correctly.
This prevents the seek bar from updating its width.
The incorrect seek bar width leads to miscalculations in the question timing.
**Fix:**
To resolve this, an event is dispatched within useLayoutEffect, right before the browser paints the element. This ensures that the seek bar’s dimensions are recalculated correctly, resulting in accurate question timing on the timeline.
solved [SUP-46685](https://kaltura.atlassian.net/browse/SUP-46685)
[SUP-46685]: https://kaltura.atlassian.net/browse/SUP-46685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
=> fix (SUP-46685):  Multiple Chapters in Quiz Break the Timeline

src/ivq.tsx
**Issue:**
The cue-points of the IVQ questions are loaded when the ads are playing, therefore, they are not seen in the seek bar when the entry is playing.
**Fix:**
When all the ads are completed, remove all the cue-points and put them again, in order to see them on the seekbar.
solved [SUP-47479](https://kaltura.atlassian.net/browse/SUP-47479)
[SUP-47479]: https://kaltura.atlassian.net/browse/SUP-47479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix (SUP-47479): player with bumper prevents display of quiz timestamp on the timeline

src/ivq.tsx
**Issue:**
The cue-points of the IVQ questions are loaded when the ads are playing, therefore, they are not seen in the seek bar when the entry is playing.
The problem can be solved by add "disableMediaPreload": true, but on YouTube entry it doesn't work.
**Fix:**
When all the ads are completed, remove all the cue-points and put them again, in order to see them on the seekbar.
solved [SUP-47479](https://kaltura.atlassian.net/browse/SUP-47479)
[SUP-47479]: https://kaltura.atlassian.net/browse/SUP-47479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-47479): player with bumper prevents display of quiz timestamp on the timeline

src/ivq.tsx
**Issue:**
ALL_ADS_COMPLETED event is fired for IMA and not for bumper.
**Fix:**
Listen to AD_COMPLETED instead. each ad that is finished, remove the ivq questions and apply them again.
Also when user clicked on SKIP, the behavior supposed to be the same.
=> fix: (SUP-47479): player with bumper prevents display of quiz timestamp on the timeline

src/components/quiz-question/multi-choice/multi-choice.tsx
This solves https://kaltura.atlassian.net/browse/ADA-1783. Removing aria-multiselectable because it's invalid with role="radio"
=> fix(ADA-1783): Remove aria multiselectable

src/data-sync-manager.ts, yarn.lock
**Issue:**
player bundler contains ua-parse-js library with version 1.0.2 even we already upgrade it to 1.0.36 in playkit-js
**Fix:**
upgrade kaltura player dependencies from old version to new version.
Solves [SUP-49286](https://kaltura.atlassian.net/browse/SUP-49286)
[SUP-49286]: https://kaltura.atlassian.net/browse/SUP-49286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SUP-49286): [PwC] Security Concern: ua-parser-js@1.0.2 Vulnerability Embedded Player
