kaltura/playkit-js-ivq

- src/components/quiz-question/open-question/open-question.scss
- src/components/quiz-question/open-question/open-question.tsx
- src/components/quiz-question/quiz-question-wrapper.scss
- src/components/quiz-question/quiz-question-wrapper.tsx
- src/components/quiz-question/reflection-point/reflection-point.scss
1)  fix issue with wrong position of markers on time-line;
2) ivq-bottom-bar styles;
3) reflection point styles;
4) open-question styles;
> feat(FEV-1039): Reflection point and Open question

- src/components/quiz-question/multi-choice/multi-choice.scss
- src/components/quiz-question/multi-choice/multi-choice.tsx
- src/components/quiz-question/open-question/open-question.scss
- src/components/quiz-question/quiz-question-wrapper.scss
- src/components/quiz-question/quiz-question-wrapper.tsx
- src/components/quiz-question/reflection-point/reflection-point.scss
- src/components/quiz-question/true-false/true-false.scss
- src/theme.scss
1) made styles for multiple-answer;
2) fix overlay styles (!important selector required to overwrite responsive overlay styles);
3) small fixes for other type of questions to handle responsiveness;
> feat(FEV-1035): multiple choice and multiple answer question types

- src/data-sync-manager.ts
- src/ivq.tsx
- src/questions-manager.tsx
1) Skip question feature;
2) Add types;
3) Destroy event manager on plugin destroy;
> feat(FEV-1095): I as a user want to skip the question in quiz

- src/components/quiz-question/multi-choice/multi-choice.tsx
- src/components/quiz-question/open-question/open-question.tsx
- src/components/quiz-question/quiz-question-wrapper.tsx
- src/components/quiz-question/true-false/true-false.tsx
- src/data-sync-manager.ts
- src/providers/response-types/kaltura-quiz.ts
- src/questions-manager.tsx
- src/theme.scss
- src/types/quizTypes.ts
- src/types/quizTypesUI.ts
1) Allow\disallow change answers;
2) small fix for styles on hover;
> feat(FEV-1097): I as a quiz creator want to enable/disable to change answers

- src/data-sync-manager.ts
- src/ivq.tsx
- src/questions-manager.tsx
- src/quiz-middleware.ts
1) check quiz params and activate seek control;
2) Handle and restrict seeking forward if option is not allowed;
> feat(FEV-1095): Seeking feature

- src/components/quiz-question/multi-choice/multi-choice.scss
- src/components/quiz-question/open-question/open-question.scss
- src/components/quiz-question/reflection-point/reflection-point.scss
- src/components/quiz-question/true-false/true-false.scss
- src/components/quiz-review/question-list-review/question-list-review.scss
- src/components/quiz-submit/quiz-submit.scss
- src/ivq.tsx
- src/theme.scss
- Ivq responsiveness;
resolves:
https://kaltura.atlassian.net/browse/FEV-1201
https://kaltura.atlassian.net/browse/FEV-1194
https://kaltura.atlassian.net/browse/FEV-1198
> feat(FEV-1196): IVQ responsiveness

- src/ivq.tsx
display welcome slate once quiz data ready
> fix(FEV-1203): Welcome page displayed only for entry owner and co-editors

- src/components/quiz-question/multi-choice/multi-choice.scss
- src/components/quiz-question/open-question/open-question.scss
- src/components/quiz-question/quiz-question-wrapper.scss
- src/components/quiz-question/reflection-point/reflection-point.scss
- src/components/quiz-question/true-false/true-false.scss
- src/components/quiz-review/question-list-review/question-list-review.scss
- src/components/quiz-review/question-review/question-review.scss
- src/theme.scss
- remove scrollbars;
- fixed char-counter for open-question;
- small style fixes for different type of questions;
> fix(FEV-1198): A redundant scrollbar is displayed on the submission page

- src/data-sync-manager.ts
- src/questions-visual-manager.tsx
- src/types/quizTypes.ts
disable answers if allowAnswerUpdate not allowed
> fix(FEV-1206): Question buttons and text inputs are disabled

- src/components/quiz-question/open-question/open-question.tsx
- src/components/quiz-question/quiz-question-wrapper.tsx
- src/questions-visual-manager.tsx
- update question component on manual jump between questions or if next question has same start-time;
- use delta 0.3sec to prevent unnecessary seek;
> fix(FEV-1200): Moving between questions at the same timepoint is not smooth- the video frame should NOT be seen while moving

- src/components/a11y-wrapper/a11y-wrapper.tsx
- src/components/a11y-wrapper/index.ts
- src/components/quiz-question/multi-choice/multi-choice.tsx
- src/components/quiz-question/open-question/open-question.scss
- src/components/quiz-question/question-addons/question-addons.scss
- src/components/quiz-question/question-addons/question-addons.tsx
- src/components/quiz-question/quiz-question-wrapper.tsx
- src/components/quiz-question/true-false/true-false.tsx
- src/components/quiz-review/question-list-review/question-list-review.tsx
- src/components/quiz-review/question-review/question-review.tsx
- src/components/quiz-review/quiz-review.tsx
- src/theme.scss
- src/types/quizTypesUI.ts
> feat(FEV-1032): I as a user want the V7 quiz to be accessible

- src/ivq.tsx
- show welcome page only if `autoplay` disabled
> fix(FEV-1199): Welcome page does not work properly when Autoplay is on

- src/components/quiz-review/question-review/question-review.tsx
- src/providers/response-types/kaltura-quiz-answer.ts
> fix(FEV-1208): WHY (explanation) is not displayed on the player for Guest role

- src/ivq.tsx
> fix(FEV-1224): When include answers is set to OFF the score information will not be displayed after submission

- src/components/quiz-question/multi-choice/multi-choice.scss
- src/components/quiz-question/open-question/open-question.scss
- src/components/quiz-question/reflection-point/reflection-point.scss
- src/components/quiz-question/true-false/true-false.scss
- src/components/quiz-review/question-review/question-review.scss
- src/components/quiz-submit/quiz-submit.scss
increased line-height to avoid scrollbars
> fix(FEV-1198): Redundant scrollbars is displayed in IVQ plugin

- src/components/ivq-bottom-bar/ivq-bottom-bar.tsx
- src/components/ivq-overlay/ivq-overlay.tsx
- src/components/quiz-question/multi-choice/multi-choice.scss
- src/components/quiz-question/multi-choice/multi-choice.tsx
- src/components/quiz-question/open-question/open-question.scss
- src/components/quiz-question/open-question/open-question.tsx
- src/components/quiz-question/question-addons/question-addons.tsx
- src/components/quiz-question/quiz-question-wrapper.scss
- src/components/quiz-question/quiz-question-wrapper.tsx
- src/components/quiz-question/reflection-point/reflection-point.scss
- src/components/quiz-question/reflection-point/reflection-point.tsx
- src/components/quiz-question/true-false/true-false.scss
- src/components/quiz-question/true-false/true-false.tsx
- src/components/quiz-review/question-list-review/question-list-review.scss
- src/components/quiz-review/question-list-review/question-list-review.tsx
- src/components/quiz-review/question-review/question-review.tsx
- src/components/quiz-submit/quiz-submit.tsx
- src/components/timeline/timeline-marker.tsx
- src/components/welcome-screen/welcome-screen.tsx
- src/ivq.tsx
- src/theme.scss
- translations/en.i18n.json
1) Welcome page - Download button a11y (https://kaltura.atlassian.net/browse/FEV-1227);
2) Welcome page - content a11y (https://kaltura.atlassian.net/browse/FEV-1229);
3) Reflection point text a11y (https://kaltura.atlassian.net/browse/FEV-1231);
4) Safari Voiceover issue fixes;
5) Focus on "Continue" question; (https://kaltura.atlassian.net/browse/FEV-1228)
> fix(FEV-1234): Safari Voiceover issues and other small a11y fixes

- src/components/timeline/timeline-marker.tsx
- src/ivq.tsx
- src/types/quizTypesUI.ts
- displays timeline preview only for video type of entries
> fix(FEV-1255): Quiz doesn't work properly for audio entries

- package.json
- src/data-sync-manager.ts
- src/ivq.tsx
- src/questions-visual-manager.tsx
- yarn.lock
1) reset ivq plugin on media-switch;
2) upd dependencies (use sass instead of deprecated node-sass);
> fix(FEV-1277): The quiz review and quiz questions shown on other non quiz entries

- package.json
- yarn.lock
> fix(FEV-1302): Cue points fails to be selected after the user selects it for the first time

- src/ivq.tsx
- yarn.lock
1) save and restore playlist configuration;
2) upd kaltura-player;
> fix(FEV-1290): When auto continue is set to true the quiz review/submit is not shown to the user

- src/components/ivq-bottom-bar/ivq-bottom-bar.tsx
- src/components/quiz-question/quiz-question-wrapper.tsx
- src/components/quiz-review/question-review/question-review.tsx
- src/components/quiz-review/quiz-review.tsx
- src/ivq.tsx
- src/questions-visual-manager.tsx
- src/types/IvqConfig.ts
1) use player seekBar in quiz layouts;
2) fix click on marker preview;
3) move "GuiArea" to global const;
> fix(FEV-1277): Player seek-bar markers doesn't disappears on media switch

- src/components/ivq-overlay/ivq-overlay.scss
- src/ivq.tsx
hide play-next overlay if ivq overlay active
> fix(FEV-1292): When Quiz entry is present and auto continue false the quiz submit/review would overlap the navigate to next entry

- src/ivq.tsx
PR depends on https://github.com/kaltura/playkit-js-kaltura-cuepoints/pull/35
> fix(FEV-1291): youtube support

- src/data-sync-manager.ts
- src/ivq.tsx
- src/utils.ts
1) if quizUserEntry doesn't exist or current quizUserEntry submitted but user has more attempts - create new quizUserEntry;
2) better error handling;
3) fix issue when version of quizUserEntry doesn't defined (guest mode case);
4) better logs;
> fix(FEV-1328): Removed Quiz Attempt is kept after the user plays the entry quiz

- translations/en.i18n.json
- translations/ko.i18n.json
> feat(FEV-1422): Quiz plugin localisation (KO)

- src/components/ivq-overlay/ivq-overlay.scss
- src/components/quiz-question/question-addons/question-addons.scss
- src/components/quiz-question/quiz-question-wrapper.tsx
- src/components/quiz-review/question-icon/question-icon.scss
- src/components/quiz-review/question-list-review/question-list-review.scss
- src/components/quiz-review/question-list-review/question-list-review.tsx
- src/components/quiz-review/question-review/question-review.scss
- src/components/quiz-review/question-review/question-review.tsx
- src/components/quiz-submit/quiz-submit.scss
- src/components/quiz-submit/quiz-submit.tsx
- src/components/spinner/spinner.scss
- src/components/welcome-screen/welcome-screen.scss
- src/components/welcome-screen/welcome-screen.tsx
- src/theme.scss
> fix(FEV-1446): For true\false and open question there is a scroll arrows when the page set to Korean language.

- translations/ko.i18n.json
> fix(FEV-1422): Quiz plugin localization

- package.json
Requires changes in [cuepoints](https://github.com/kaltura/playkit-js-kaltura-cuepoints), [timeline](https://github.com/kaltura/playkit-js-timeline).
> Add new Bundler metadata

- src/data-sync-manager.ts
change initial retake quiz attempts
> fix(FEV-1529): Retake button present for anonymous users even if the quiz is set not to allow multiple attempts

- src/components/ivq-overlay/ivq-overlay.tsx
- src/components/quiz-question/multi-choice/multi-choice.scss
- src/components/quiz-question/multi-choice/multi-choice.tsx
- src/components/quiz-question/open-question/open-question.scss
- src/components/quiz-question/open-question/open-question.tsx
- src/components/quiz-question/quiz-question-wrapper.tsx
- src/components/quiz-question/reflection-point/reflection-point.scss
- src/components/quiz-question/reflection-point/reflection-point.tsx
- src/components/quiz-question/true-false/true-false.scss
- src/components/quiz-question/true-false/true-false.tsx
- src/components/quiz-review/question-list-review/question-list-review.scss
- src/components/quiz-review/question-list-review/question-list-review.tsx
- src/components/quiz-review/question-review/question-review.scss
- src/components/quiz-review/question-review/question-review.tsx
- src/components/timeline/timeline-marker.tsx
- src/ivq.tsx
- src/theme.scss
- src/types/quizTypesUI.ts
1. Questions in the timeline bar are not readable with mac voice over
2. Question number should be read before the question title 
3. True/False answers are not readable
4. True/False answer review is not readable
> fix(FEV-1590): Mac voice over issues

- src/components/timeline/timeline-marker.tsx
> fix(FEV-1590): fix hooks issue

- src/components/timeline/timeline-marker.tsx
- src/ivq.tsx
init methods inside useMemo hook
> fix(FEV-1609): ivq plugin cause player slowness

- src/components/welcome-screen/welcome-screen.scss
- src/components/welcome-screen/welcome-screen.tsx
- src/data-sync-manager.ts
- src/ivq.tsx
- translations/en.i18n.json
- translations/ko.i18n.json
added instructions message and available attempts message to the welcome screen.
solves FEV-1611
> fix(FEV-1611):V7 player quiz - instructions and available attempts don't appear

- src/questions-visual-manager.tsx
prevent duplication of quiz question.
The case is next - when user clicked on quiz question marker - IVQ plugin displays quiz question and force player seek to cue start-time. Sometimes it causes an issue - user already answered on quiz question and only then question cue-point become active (that causes ivq plugin display the same question one more time).
> fix(FEV-1643): When answering a quiz question the question shows twice before it moves on

- src/components/ivq-popup/ivq-popup.tsx
- translations/en.i18n.json
> fix(FEV-1644): "Quiz completed" popups doesn't match the design.

- src/components/ivq-popup/ivq-pupup.scss
> fix(FEV-1648): Dual screen and ivq (new popups) doesn't work properly together.

- cypress/e2e/ivq.cy.ts
- src/components/ivq-popup/ivq-popup.tsx
- src/data-sync-manager.ts
- src/ivq.tsx
- translations/en.i18n.json
1) fixed issue when ivq popup appears with score 0/100 before quiz submitted;
2) quiz popup changes: text changed from “The quiz submitted.” to "Quiz submitted";
> fix(FEV-1652): "Quiz submitted" popup (with scores) doesn't match the design.

- src/components/ivq-bottom-bar/ivq-bottom-bar.tsx
- src/components/quiz-question/multi-choice/multi-choice.tsx
- src/components/quiz-question/quiz-question-wrapper.tsx
- add aria-disabled to continue button and next/prev arrow buttons
- add the text of an answer to its aria-label
Solves [FEC-12922](https://kaltura.atlassian.net/browse/FEC-12922)
[FEC-12922]: https://kaltura.atlassian.net/browse/FEC-12922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-12922): fix a11y issues

- translations/ko.i18n.json
add korean translation to "Close".
Solves [FEV-1661](https://kaltura.atlassian.net/browse/FEV-1661)
[FEV-1661]: https://kaltura.atlassian.net/browse/FEV-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEV-1661): add translation

- cypress/e2e/ivq-QuizQuestionChanged-event.cy.ts
- cypress/fixtures/ivq_QuizQuestionChanged_event/add_cuepoint_response.json
- cypress/fixtures/ivq_QuizQuestionChanged_event/cues_1_question.json
- cypress/fixtures/ivq_QuizQuestionChanged_event/quiz_answers.json
- cypress/fixtures/ivq_QuizQuestionChanged_event/quiz_ban_seek_enabled.json
- cypress/fixtures/ivq_QuizQuestionChanged_event/quiz_multiple_attempts.json
- package-lock.json
- src/ivq.tsx
- src/questions-visual-manager.tsx
Solves [FEC-13089](https://kaltura.atlassian.net/browse/FEC-13089)
[FEC-13089]: https://kaltura.atlassian.net/browse/FEC-13089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-13089): dispatch QuestionChanged event in onContinue flow when answer is the same

- .github/workflows/common_test.yml
- cypress/e2e/ivq.cy.ts
- package.json
- src/components/ivq-bottom-bar/ivq-bottom-bar.tsx
- src/components/ivq-popup/ivq-popup.tsx
- src/components/quiz-question/multi-choice/multi-choice.tsx
- src/components/quiz-question/question-addons/question-addons.tsx
- src/components/quiz-question/quiz-question-wrapper.tsx
- src/components/quiz-question/true-false/true-false.tsx
- src/components/quiz-review/question-list-review/question-list-review.tsx
- src/components/quiz-review/question-review/question-review.tsx
- src/components/quiz-submit/quiz-submit.tsx
- src/components/timeline/timeline-marker.tsx
- src/components/welcome-screen/welcome-screen.tsx
- src/ivq.tsx
- yarn.lock
1) upd common repo;
2) upd imports (use es6 modules);
3) add GH action for running tests;
4) upd e2e tests;
> chore: upd common repo, upd tests and gh actions

- cypress/e2e/ivq-question-changed-event.cy.ts
- cypress/fixtures/ivq_QuizQuestionChanged_event/cues_1_question.json
- src/data-sync-manager.ts
- src/ivq.tsx
solves: https://kaltura.atlassian.net/browse/FEC-13179
pass onClick handler to Navigation plugin
> fix(FEC-13179): when navigating in the quiz to a question in the KS it's not changing the question in the overlay

- translations/de.i18n.json
issue:
de translation is incorrect
solution:
fix the translation
> fix(SUP-38427):Player translation wrong for Quiz

- src/components/quiz-question/multi-choice/multi-choice.tsx
- src/components/quiz-question/open-question/open-question.tsx
- src/components/quiz-question/question-addons/question-addons.tsx
- src/components/quiz-question/reflection-point/reflection-point.tsx
- src/components/quiz-question/true-false/true-false.tsx
- src/components/quiz-review/question-list-review/question-list-review.tsx
- src/components/quiz-submit/quiz-submit.tsx
- src/components/welcome-screen/welcome-screen.tsx
issue:
role="text" is not a valid role
solution:
remove role="text"
solves ADA-30
> fix(ADA-30):[V7-Acc] remove role="text" label from any container as it is not a valid role and it has not been approved

- .github/workflows/run_tests.yaml
- src/ivq.tsx
- src/questions-visual-manager.tsx
- src/types/ivqEventTypes.ts
Add Events (used by kava analytics)
Solves FEC-13718
> feat(FEC-13718): [Quiz Plugin]: Add Events (used by kava analytics)

- package.json
- src/questions-visual-manager.tsx
- yarn.lock
Resolves FEC-13845
Related PR: https://github.com/kaltura/playkit-js-kava/pull/182
> fix(FEC-13845): Add Events (used by kava analytics) | Quiz_skip_question "buttonValue" doesn't show question number.

- cypress/e2e/ivq.cy.ts
- src/data-sync-manager.ts
- src/index.ts
- src/ivq.tsx
- src/providers/response-types/kaltura-quiz.ts
- src/providers/response-types/kaltura-user-entry.ts
- src/types/quizTypes.ts
- src/utils.ts
Example:
1. use `setQuizAttributes`  API
```
player.loadMedia({ entryId: '1_blvk75b5' }).then(() => {
player.getService("ivq").setQuizAttributes();
});
```
2. add quiz cues
```
player.cuePointManager.addCuePoints([....]);
```
> feat(FEC-14234): quiz preview mode

- translations/de.i18n.json
- translations/es.i18n.json
- translations/ja.i18n.json
- translations/ko.i18n.json
add translations for disable seek message
solve [SUP-46942](https://kaltura.atlassian.net/browse/SUP-46942)
[SUP-46942]: https://kaltura.atlassian.net/browse/SUP-46942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-46942):[eLearning] Seek forward notification inquiry

- src/components/quiz-question/quiz-question-wrapper.tsx
Issue:
Don't receive from the backend side the field "questionType", therefore the questions are not seen to the user.
Fix:
Add default handler to this special case, and treat to the question as multiple question.
Solved [SUP-46658](https://kaltura.atlassian.net/browse/SUP-46658)
[SUP-46658]: https://kaltura.atlassian.net/browse/SUP-46658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: SUP-46658:  V7 player freezes when loading quiz question

- package.json
- src/components/ivq-overlay/ivq-overlay.scss
- src/components/ivq-overlay/ivq-overlay.tsx
- src/components/quiz-review/question-list-review/question-list-review.tsx
- src/components/quiz-submit/quiz-submit.tsx
- yarn.lock
This pr solves https://kaltura.atlassian.net/browse/ADA-2332
> Fix(ADA-2332): Focus management on Quiz modals

- src/components/quiz-question/quiz-question-wrapper.tsx
This solves https://kaltura.atlassian.net/browse/ADA-2093
> fix(ADA-2093): Stop focusing continue button after selecting answer

- src/ivq.tsx
Reverts kaltura/playkit-js-ivq#159
> Revert "fix (SUP-47479): player with bumper prevents display of quiz timestamp on the timeline"

- src/components/quiz-review/question-list-review/question-list-review.tsx
This is fixing https://kaltura.atlassian.net/browse/ADA-2332. Per Talia, focusing on the close button by default on Question list review
> Fix(ADA-2332) - Focus list review close button

- src/components/quiz-question/multi-choice/multi-choice.tsx
This PR solves this issue: https://kaltura.atlassian.net/browse/ADA-2707
> Fix(ADA-2707) - Adding aria attribute for multi choice radiogroup

- src/components/quiz-question/quiz-question-wrapper.tsx
- src/components/quiz-review/question-list-review/question-list-review.tsx
- src/components/quiz-submit/quiz-submit.tsx
This solves https://kaltura.atlassian.net/browse/ADA-2797
> fix(ADA-2797): Fix Quiz issues

- src/components/ivq-popup/ivq-popup.tsx
This fixes https://kaltura.atlassian.net/browse/ADA-2706 by changing role alert to dialog and creating a live region so that SR is announcing the popup
> fix(ADA-2706): Use role dialog

- src/components/ivq-overlay/ivq-overlay.scss
This solves https://kaltura.atlassian.net/browse/ADA-2303
> fix(ADA-2303): Change focus indicator thickness

- src/components/quiz-question/multi-choice/multi-choice.scss
This fixes https://kaltura.atlassian.net/browse/FEC-14603
> fix(FEC-14603): Fix focus indicator margin cut

- src/components/ivq-popup/ivq-popup.tsx
This solves regression https://kaltura.atlassian.net/browse/FEC-14592. The buttons would not be announced, only the their texts, as agreed with Julien
> fix(FEC-14592): Announce popup buttons text

- CHANGELOG.md
- package.json
- src/components/ivq-popup/ivq-popup.tsx
- src/components/ivq-popup/ivq-pupup.scss
- src/components/quiz-question/multi-choice/multi-choice.scss
- src/ivq.tsx
- translations/en.i18n.json
- yarn.lock
This solves https://kaltura.atlassian.net/browse/FEC-14593. Related to https://github.com/kaltura/playkit-js-ui/pull/1066 that adds initial focus indicator
> fix(FEC-14593): Add shortcut to quiz popup

- package.json
- src/components/ivq-popup/ivq-popup.tsx
- translations/en.i18n.json
- yarn.lock
This fixes https://kaltura.atlassian.net/browse/FEC-14593
> fix(FEC-14593): Complete IVQ popup shortcut
